/* ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                FINAL WORKSHOP
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ */
-- QUESTION 01
SELECT (A.C1 + B.C2 + C.C3 + D.C4) "총 데이터 개수"
FROM   ( SELECT COUNT(*) C1 FROM TB_BOOK ) A,
       ( SELECT COUNT(*) C2 FROM TB_BOOK_AUTHOR ) B,
       ( SELECT COUNT(*) C3 FROM TB_PUBLISHER ) C,
       ( SELECT COUNT(*) C4 FROM TB_WRITER ) D;
     
-- QUESTION 02
SELECT  TABLE_NAME,
        COLUMN_NAME,
        DATA_TYPE,
        DATA_DEFAULT,
        NULLABLE,
        CONSTRAINT_NAME,
        CONSTRAINT_TYPE,
        R_CONSTRAINT_NAME
FROM    USER_CONSTRAINTS
JOIN    USER_TAB_COLUMNS USING (TABLE_NAME);

-- QUESTION 03
SELECT  BOOK_NO, BOOK_NM
FROM    TB_BOOK
WHERE   LENGTH(BOOK_NM) >= 25;

-- QUESTION 04
SELECT   NM 이름, OT 사무실전화번호, HT 집전화번호, MN 휴대폰번호
FROM     ( SELECT  WRITER_NM NM,
                   OFFICE_TELNO OT,
                   HOME_TELNO HT,
                   MOBILE_NO MN,
                   RANK() OVER (ORDER BY WRITER_NM ASC) RNK
           FROM TB_WRITER
           WHERE MOBILE_NO LIKE '019%'
                 AND WRITER_NM LIKE '김%' ) -- 인라인 뷰
WHERE    RNK = 1;

-- QUESTION 05
SELECT  COUNT(*)
FROM    (SELECT DISTINCT WRITER_NO
         FROM   TB_BOOK_AUTHOR
         WHERE  COMPOSE_TYPE = '옮김') F,
         TB_WRITER W
WHERE   F.WRITER_NO = W.WRITER_NO;

-- QUESTION 06
SELECT   COMPOSE_TYPE 저작형태, COUNT(*) 도서수량
FROM     TB_BOOK_AUTHOR
WHERE    COMPOSE_TYPE IS NOT NULL
GROUP BY COMPOSE_TYPE
HAVING   COUNT(*) >= 300;

-- QUESTION 07
SELECT  B 최신책이름, A 발행일자, P 출판사
FROM    ( SELECT ISSUE_DATE A, BOOK_NM B, PUBLISHER_NM P
          FROM TB_BOOK
          ORDER BY 1 DESC )
WHERE ROWNUM = 1;

-- QUESTION 08
SELECT  작가, 권수
FROM    ( SELECT    WRITER_NM 작가,
                    COUNT(*) 권수,
                    RANK() OVER(ORDER BY COUNT(*) DESC) RNK
          FROM      TB_WRITER W, TB_BOOK_AUTHOR A
          WHERE     W.WRITER_NO = A.WRITER_NO
          GROUP BY  WRITER_NM )
WHERE   RNK < 4;

-- QUESTION 09
    
--select issue_date from tb_book
--order by 1;
-- 문제 잘못봄 ㅋ
-- UPDATE TB_WRITER
-- SET REGIST_DATE = ( SELECT  A
--                     FROM    (SELECT ISSUE_DATE A
--                              FROM TB_BOOK
--                              ORDER BY 1)
--                     WHERE ROWNUM = 1 );
                    
UPDATE TB_WRITER TW
SET REGIST_DATE = ( SELECT  F.MB
                    FROM    ( SELECT ROW_NUMBER() OVER (PARTITION BY WRITER_NO ORDER BY MIN(BOOK_NO)) AS ROWN,
                                     WRITER_NO , 
                                     TO_DATE(SUBSTR(MIN(BOOK_NO),1,8), 'RR/MM/DD') MB
                                     FROM   TB_BOOK_AUTHOR
                                     GROUP BY WRITER_NO ) F
                    WHERE F.ROWN = 1
                          AND TW.WRITER_NO = F.WRITER_NO );
                    
SELECT  WRITER_NO, REGIST_DATE FROM TB_WRITER
ORDER BY 1;
SELECT  WRITER_NO, BOOK_NO FROM TB_BOOK_AUTHOR
ORDER BY 1, 2;
rollback;

-- QUESTION 10
CREATE TABLE TB_BOOK_TRANSLATOR
(
 BOOK_NO        VARCHAR2(10),
 WRITER_NO      VARCHAR2(10),
 TRANS_LANG     VARCHAR2(60),
 CONSTRAINT PK_BOOK_TRANSLATOR PRIMARY KEY (BOOK_NO, WRITER_NO),
 CONSTRAINT FK_BOOK_TRANSLATOR_01 FOREIGN KEY (BOOK_NO) REFERENCES TB_BOOK(BOOK_NO),
 CONSTRAINT FK_BOOK_TARNSLATOR_02 FOREIGN KEY (WRITER_NO) REFERENCES TB_WRITER(WRITER_NO)
);

COMMENT ON COLUMN TB_BOOK_TRANSLATOR.BOOK_NO IS '도서번호';
COMMENT ON COLUMN TB_BOOK_TRANSLATOR.WRITER_NO IS '작가번호';
COMMENT ON COLUMN TB_BOOK_TRANSLATOR.TRANS_LANG IS '번역언어';

-- QUESTION 11
INSERT INTO TB_BOOK_TRANSLATOR (BOOK_NO, WRITER_NO)
(
 SELECT BOOK_NO, WRITER_NO
 FROM   TB_BOOK_AUTHOR
 WHERE  COMPOSE_TYPE IN ('옮김','역주','편역','공역')
);

DELETE TB_BOOK_AUTHOR
WHERE COMPOSE_TYPE IN ('옮김','역주','편역','공역');

ROLLBACK;
SELECT  * FROM TB_BOOK_TRANSLATOR;
SELECT  DISTINCT COMPOSE_TYPE FROM TB_BOOK_AUTHOR
WHERE COMPOSE_TYPE = '역주';

-- QUESTION 12
SELECT  B.BOOK_NM, W.WRITER_NM
FROM    TB_BOOK_TRANSLATOR T, TB_WRITER W, TB_BOOK B
WHERE   T.WRITER_NO = W.WRITER_NO
        AND T.BOOK_NO = B.BOOK_NO
        AND T.BOOK_NO LIKE '2007%';
        
-- QUESTION 13
CREATE OR REPLACE VIEW VW_BOOK_TRANSLATOR
AS  SELECT  *
    FROM    (SELECT ISSUE_DATE
             FROM   TB_BOOK B, TB_BOOK_TRANSLATOR T
             WHERE  B.BOOK_NO = T.BOOK_NO)
WITH READ ONLY;

select  * from vw_book_translator;

-- QUESTION 14
INSERT INTO TB_PUBLISHER
VALUES ('춘 출판사','02-6710-3737',DEFAULT);

-- QUESTION 15
SELECT   WRITER_NM 이름, COUNT(*) "동명인 수"
FROM     TB_WRITER
GROUP BY WRITER_NM
HAVING   COUNT(*) > 1;

-- QUESTION 16
UPDATE  TB_BOOK_AUTHOR
SET     COMPOSE_TYPE = '지음'
WHERE   COMPOSE_TYPE IS NULL;

COMMIT;

-- QUESTION 17
SELECT  WRITER_NM, 
        OFFICE_TELNO
FROM    TB_WRITER
WHERE   OFFICE_TELNO LIKE '02%'
        AND LENGTH(OFFICE_TELNO) = 11;

        
-- QUESTION 18
SELECT  WRITER_NM,  2006 - TO_CHAR(REGIST_DATE, 'YYYY')
FROM    TB_WRITER
WHERE   2006 - TO_CHAR(REGIST_DATE, 'YYYY') >= 31;

-- QUESTION 19
SELECT   BOOK_NM 도서명, 
         PRICE 가격,
         CASE WHEN STOCK_QTY < 5 THEN '추가주문필요'
              ELSE '소량보유'
         END AS 재고상태
FROM     TB_BOOK
WHERE    PUBLISHER_NM = '황금가지'
         AND STOCK_QTY < 10
ORDER BY 3 DESC, 1;

-- QUSETION 20
SELECT  도서명, TW.WRITER_NM 저자, 역자
FROM    ( SELECT  B.BOOK_NM 도서명, W.WRITER_NM 역자, A.WRITER_NO WN
          FROM    TB_BOOK B, TB_WRITER W, TB_BOOK_TRANSLATOR T, TB_BOOK_AUTHOR A
          WHERE   T.BOOK_NO = B.BOOK_NO
                  AND T.WRITER_NO = W.WRITER_NO
                  AND A.BOOK_NO = B.BOOK_NO
                  AND B.BOOK_NM = '아타트롤' ) F,
        TB_WRITER TW
WHERE   TW.WRITER_NO = F.WN;

-- QUESTION 21
SELECT  BOOK_NM 도서명, STOCK_QTY 재고수량, PRICE "가격(Org)",
        (PRICE * 0.8) "가격(New)"
FROM    TB_BOOK
WHERE   TO_CHAR(SYSDATE, 'YYYY') - TO_CHAR(ISSUE_DATE, 'YYYY') > 30
        AND STOCK_QTY > 89
ORDER BY 2 DESC, 4 DESC, 1;

