-- TEST 01 2019.01.09

-- QUESTION 01
SELECT   COUNT(*) 학생수
FROM     TB_STUDENT
WHERE    DEPARTMENT_NO = '003' 
         AND SUBSTR(ENTRANCE_DATE, 1, 2) = '01';

-- QUESTION 02
SELECT   CATEGORY 계열,
         DEPARTMENT_NAME 학과이름,
         CAPACITY 정원
FROM     TB_DEPARTMENT
WHERE    CATEGORY = '공학' AND
         CAPACITY BETWEEN 20 AND 30
ORDER BY 2;

-- QUESTION 03
SELECT   CATEGORY 계열,
         COUNT(*) 학과수
FROM     TB_DEPARTMENT
WHERE    CATEGORY LIKE '%학%'
GROUP BY CATEGORY
ORDER BY 2 DESC;

-- QUESTION 04
SELECT   PROFESSOR_NAME 교수이름,
         SUBSTR(PROFESSOR_SSN, 1, 2) 출생년도,
         PROFESSOR_ADDRESS 주소
FROM     TB_PROFESSOR
WHERE    DEPARTMENT_NO = '002'
ORDER BY 2;

-- QUESTION 05
SELECT   DEPARTMENT_NO 학과번호,
         STUDENT_NAME 학생이름,
         CASE ABSENCE_YN WHEN 'Y' THEN '휴학'
            ELSE '정상'
         END
FROM     TB_STUDENT
WHERE    DEPARTMENT_NO = '001' 
         AND STUDENT_ADDRESS LIKE '%서울%'
ORDER BY 2;

-- QUESTION 06
SELECT   RPAD(SUBSTR(STUDENT_SSN, 1, INSTR(STUDENT_SSN, '-')+1), 14, '*') "[주민번호]",
         STUDENT_NAME 학생이름
FROM     TB_STUDENT
WHERE    SUBSTR(STUDENT_SSN, 1, 2) = '80' 
         AND SUBSTR(STUDENT_SSN, 8, 1) IN (2, 4) 
         AND STUDENT_NAME LIKE '김%'
ORDER BY 2;

-- QUESTION 07
SELECT   DEPARTMENT_NAME 학과이름, 
         CAPACITY 정원,
         CASE WHEN CAPACITY > 40 THEN '대강의실'
              WHEN CAPACITY > 30 THEN '중강의실'
                ELSE '소강의실'
         END 강의실크기
FROM     TB_DEPARTMENT
WHERE    CATEGORY LIKE '예체능%'
ORDER BY 2 DESC, 1;

-- QUESTION 08
SELECT   STUDENT_NAME 학생이름,
         TO_CHAR(ENTRANCE_DATE, 'RRRR"년"MM"월"DD"일"') 입학일자,
         FLOOR( MONTHS_BETWEEN (SYSDATE, ENTRANCE_DATE) / 12) || '년' "입학후기간(년)" 
FROM     TB_STUDENT
WHERE    EXTRACT(YEAR FROM ENTRANCE_DATE) < 2000
         AND (STUDENT_ADDRESS LIKE '경기%'
         OR  STUDENT_ADDRESS LIKE '인천%')
ORDER BY 3 DESC, 1;

-- QUESTION 09 - NOT YET
SELECT   DEPARTMENT_NO 학과번호,
         MIN(TRUNC(MONTHS_BETWEEN(SYSDATE, TO_DATE(SUBSTR(PROFESSOR_SSN,1, 2)+1900, 'RRRR'))/12))
FROM     TB_PROFESSOR
WHERE    PROFESSOR_ADDRESS LIKE '서울%'
GROUP BY DEPARTMENT_NO
ORDER BY 2;

-- QUESTION 10
SELECT   DEPARTMENT_NO 학과번호,
         STUDENT_NAME 학생이름,
         COACH_PROFESSOR_NO 지도교수번호,
         TO_CHAR(ENTRANCE_DATE, 'RRRRMMDD') ||'년' 입학년도
FROM     TB_STUDENT
WHERE    ENTRANCE_DATE BETWEEN '2005/01/01' AND '2006/12/31'
         AND STUDENT_ADDRESS IS NULL
ORDER BY 4, 1;

----이건 실습으로 다 풀어야함.
-- QUESTION 11
SELECT  COACH_PROFESSOR_NO
FROM    TB_STUDENT
WHERE   STUDENT_NAME = '서가람';

SELECT   SUBSTR(TERM_NO, 1, 4) 년도,
         ROUND(AVG(POINT), 1) 평점
FROM     TB_GRADE
JOIN     TB_STUDENT USING (STUDENT_NO)
WHERE    COACH_PROFESSOR_NO = ( SELECT  COACH_PROFESSOR_NO
                                FROM    TB_STUDENT
                                WHERE   STUDENT_NAME ='서가람' )
GROUP BY SUBSTR(TERM_NO, 1, 4)
ORDER BY 1 DESC;

-- QUESTION 12
SELECT   DEPARTMENT_NAME 학과명, 학생명, 입학일자
FROM     ( SELECT  STUDENT_NAME 학생명, DEPARTMENT_NO, ENTRANCE_DATE 입학일자
           FROM    TB_STUDENT
           WHERE   SUBSTR(STUDENT_SSN, 8, 1) IN (1, 3)
                   AND ABSENCE_YN = 'Y'
                   AND ENTRANCE_DATE BETWEEN '2001/01/01' AND SYSDATE) F,
           TB_DEPARTMENT D
WHERE    F.DEPARTMENT_NO = D.DEPARTMENT_NO
ORDER BY 3 DESC;

-- QUESTION 13
SELECT   PROFESSOR_NAME, 
         COUNT(*)
FROM     TB_PROFESSOR P, TB_CLASS_PROFESSOR C, TB_STUDENT S
WHERE    P.PROFESSOR_NO = C.PROFESSOR_NO(+)
         AND S.COACH_PROFESSOR_NO = P.PROFESSOR_NO
         AND C.CLASS_NO IS NULL
GROUP BY PROFESSOR_NAME;

-- EXISTS
SELECT  N 지도교수, C 학생수
FROM    (SELECT   PROFESSOR_NAME N, COUNT(*) C -- 별칭처리
         FROM     TB_PROFESSOR E
         JOIN     TB_STUDENT S ON (E.PROFESSOR_NO = S.COACH_PROFESSOR_NO)
         WHERE    NOT EXISTS ( SELECT NULL
                               FROM   TB_CLASS_PROFESSOR F
                               WHERE  E.PROFESSOR_NO = F.PROFESSOR_NO )
                               GROUP BY PROFESSOR_NAME ) 
GROUP BY N, C;

-- SELECT PROFESSOR_NO FROM TB_PROFESSOR WHERE  PROFESSOR_NAME = '허문표';
-- SELECT PROFESSOR_NO FROM TB_CLASS_PROFESSOR WHERE CLASS_NO IS NULL;
-- SELECT CLASS_NO FROM TB_CLASS_PROFESSOR WHERE PROFESSOR_NO = 'P069';

-- QUESTION 14
SELECT  STUDENT_NAME, ROUND(AVG(POINT), 1), TERM_NO
FROM    ( SELECT DEPARTMENT_NO
          FROM TB_DEPARTMENT
          WHERE CATEGORY = '공학'
          GROUP BY DEPARTMENT_NO) F
JOIN    TB_STUDENT S ON (F.DEPARTMENT_NO = S.DEPARTMENT_NO)
JOIN    TB_GRADE G ON (S.STUDENT_NO = G.STUDENT_NO)
WHERE   TERM_NO LIKE '2009%'
GROUP BY STUDENT_NAME, TERM_NO
HAVING ROUND(AVG(POINT), 1) >= 4.0
ORDER BY 2 DESC;

--select point, term_no
--from tb_grade
--where student_no = 'A641040'; --and term_no like '2009%';


-- QUESTION 15
SELECT    SUBSTR(TERM_NO, 1, 4) 년도,
          SUBSTR(TERM_NO, -2, 2) 학기,
          ROUND(AVG(POINT),1 ) 평점
FROM      TB_GRADE G
JOIN     TB_STUDENT S ON (G.STUDENT_NO = S.STUDENT_NO)
JOIN     ( SELECT  DEPARTMENT_NO
           FROM    TB_STUDENT
           WHERE   STUDENT_NAME = '김고운' ) D 
         ON (D.DEPARTMENT_NO = S.DEPARTMENT_NO) 
WHERE   SUBSTR(TERM_NO, 1, 4) BETWEEN 2007 AND 2008
GROUP BY ROLLUP (SUBSTR(TERM_NO, 1, 4), SUBSTR(TERM_NO, -2, 2));

-- QUESTION 16
SELECT   SUBSTR(TERM_NO, 1, 4),
         NVL(SUBSTR(TERM_NO, -1, 2), '-'),
         ROUND(AVG(POINT), 1)
FROM     TB_GRADE
JOIN     TB_STUDENT USING (STUDENT_NO)
WHERE    TERM_NO LIKE '2004%'
         AND DEPARTMENT_NO = ( SELECT  DEPARTMENT_NO
                               FROM    TB_CLASS
                               WHERE   CLASS_NAME = '문학과생태학')
         AND SUBSTR(TERM_NO, -1, 2) IS NOT NULL
GROUP BY ROLLUP (SUBSTR(TERM_NO, -1, 2)), SUBSTR(TERM_NO, 1, 4)
ORDER BY 1;

-- QUESTION 17
SELECT   STUDENT_NAME,
         PROFESSOR_NAME
FROM     TB_STUDENT S, TB_PROFESSOR P
WHERE    P.PROFESSOR_NO = S.COACH_PROFESSOR_NO
         AND LENGTH(STUDENT_NO) = 7
         AND STUDENT_NO LIKE 'A__3%'
         AND PROFESSOR_NAME LIKE '이%'
ORDER BY 1;

-- QUESTION 18
SELECT    계열, 학과이름, COUNT(*) 학생수
FROM      ( SELECT  DEPARTMENT_NAME 학과이름, 
                    DEPARTMENT_NO, 
                    CATEGORY 계열
            FROM    TB_DEPARTMENT
            WHERE   CATEGORY = '예체능' OR CATEGORY = '의학') F
LEFT JOIN TB_STUDENT S ON (S.DEPARTMENT_NO = F.DEPARTMENT_NO) 
GROUP BY  계열, 학과이름
ORDER BY  1, 3 DESC;

-- QUESTION 19
SELECT   L.CLASS_NAME, 
         C.CLASS_NAME
FROM     ( SELECT   DEPARTMENT_NO
           FROM     TB_DEPARTMENT
           WHERE    DEPARTMENT_NAME = '행정학과' ) F
JOIN     TB_CLASS C ON (C.DEPARTMENT_NO = F.DEPARTMENT_NO)
JOIN     TB_CLASS L ON (C.CLASS_NO = L.PREATTENDING_CLASS_NO);

--SELECT  PREATTENDING_CLASS_NO FROM TB_CLASS WHERE CLASS_NAME = '정책사례연구';
--SELECT  PREATTENDING_CLASS_NO, CLASS_NAME FROM TB_CLASS WHERE CLASS_NO = 'C3048900';
--SELECT  CLASS_NAME FROM TB_CLASS WHERE PREATTENDING_CLASS_NO = 'C3048900';
--SELECT CLASS_NAME FROM TB_CLASS WHERE CLASS_NO = 'C3051900';