--2018.12.13 DAY2과제
--QUESTION_01
SELECT  DEPARTMENT_NAME "학과 명",
        CATEGORY "계열"
FROM    TB_DEPARTMENT;

--QUESTION_02
SELECT  DEPARTMENT_NAME || '의 정원은 ' || CAPACITY || ' 명 입니다.' AS "학과별 정원"
FROM    TB_DEPARTMENT;

--QUESTION_03
SELECT  STUDENT_NAME
FROM    TB_STUDENT
WHERE   DEPARTMENT_NO = '001' AND ABSENCE_YN = 'Y' AND STUDENT_SSN LIKE '_______2%';

--QUESTION_04
SELECT  STUDENT_NAME
FROM    TB_STUDENT
WHERE   STUDENT_NO IN('A513079','A513090','A513091','A513110','A513119');

--QUESTION_05
SELECT  DEPARTMENT_NAME
        CATEGORY
FROM    TB_DEPARTMENT
WHERE   CAPACITY BETWEEN 20 AND 30;

--QUESTION_06
SELECT  PROFESSOR_NAME
FROM    TB_PROFESSOR
WHERE   DEPARTMENT_NO IS NULL;

--QUESTION_07
SELECT  STUDENT_NAME
FROM    TB_STUDENT
WHERE   DEPARTMENT_NO IS NULL;

--QUESTION_08
SELECT  CLASS_NO
FROM    TB_CLASS
WHERE   PREATTENDING_CLASS_NO IS NOT NULL;

--QUESTION_09
SELECT DISTINCT CATEGORY
FROM    TB_DEPARTMENT
ORDER BY CATEGORY ASC;

--QUESTION_10
SELECT  STUDENT_NO, STUDENT_NAME, STUDENT_SSN
FROM    TB_STUDENT
WHERE   (STUDENT_NO LIKE '_2_____%') AND (STUDENT_ADDRESS LIKE '전주%') AND ABSENCE_YN = 'N';