--2019.01.02 DAY3과제
--QUESTION_01
SELECT   STUDENT_NO 학번, STUDENT_NAME 이름, ENTRANCE_DATE 입학년도
FROM     TB_STUDENT
WHERE    DEPARTMENT_NO = '002'
ORDER BY ENTRANCE_DATE ASC;

--QUESTION_02
SELECT  PROFESSOR_NAME, PROFESSOR_SSN
FROM    TB_PROFESSOR
WHERE   LENGTH( PROFESSOR_NAME ) != '3';

--QUESTION_03  
SELECT   PROFESSOR_NAME 교수이름
FROM     TB_PROFESSOR
WHERE    PROFESSOR_SSN LIKE '_______1%'
--따지고보면 주영상이 어리긴한데..
ORDER BY --PROFESSOR_SSN DESC,
         SUBSTR( PROFESSOR_SSN, 1, 2 ) DESC,
         PROFESSOR_NAME ASC;
         
--QUESTION_04
SELECT  SUBSTR( PROFESSOR_NAME, -2, 2) 이름
FROM    TB_PROFESSOR;

--QUESTION_05
SELECT   STUDENT_NO, STUDENT_NAME     
FROM     TB_STUDENT
WHERE    EXTRACT( YEAR FROM ENTRANCE_DATE ) - EXTRACT( YEAR FROM TO_DATE( SUBSTR( STUDENT_SSN, 1, 6 ), 'RRMMDD' ) )  > 19
ORDER BY STUDENT_NO ASC;

--QUESTION_06
SELECT  TO_CHAR( TO_DATE('2020/12/25', 'YYYY/MM/DD'), 'DAY' )
FROM    DUAL;

--QUESTION_07
SELECT  TO_CHAR( TO_DATE('99/10/11', 'YY/MM/DD'), 'YYYY "년" MM "월" DD "일"'),
        TO_CHAR( TO_DATE('49/10/11', 'YY/MM/DD'), 'YYYY "년" MM "월" DD "일"'),
        TO_CHAR( TO_DATE('99/10/11', 'RR/MM/DD'), 'RRRR "년" MM "월" DD "일"'),
        TO_CHAR( TO_DATE('49/10/11', 'RR/MM/DD'), 'RRRR "년" MM "월" DD "일"')
FROM    DUAL;

--QUESTION_08
SELECT   STUDENT_NO, STUDENT_NAME
FROM     TB_STUDENT
WHERE    SUBSTR( STUDENT_NO, 1, 1 ) != 'A'
ORDER BY STUDENT_NO;

--QUESTION_09
SELECT  ROUND( AVG(POINT), 1 ) 평점
FROM    TB_GRADE
WHERE   STUDENT_NO = 'A517178';

--QUESTION_10
SELECT   DEPARTMENT_NO 학과번호, COUNT(*) "학생수(명)"
FROM     TB_STUDENT 
GROUP BY DEPARTMENT_NO
ORDER BY DEPARTMENT_NO;

--QUESTION_11
SELECT  COUNT(*)
FROM    TB_STUDENT
WHERE   COACH_PROFESSOR_NO IS NULL;

--QUESTION_12
SELECT   SUBSTR(TERM_NO, 1, 4 ) 년도, ROUND( AVG(POINT), 1) "년도별 평점"
FROM     TB_GRADE
WHERE    STUDENT_NO = 'A112113' 
GROUP BY SUBSTR(TERM_NO, 1, 4 );

--QUSETION_13 아싸~
SELECT   DEPARTMENT_NO 학과코드명,
         COUNT( DECODE( ABSENCE_YN, 'Y', 1 ) ) "휴학생 수"
FROM     TB_STUDENT
JOIN     TB_DEPARTMENT USING (DEPARTMENT_NO)
GROUP BY DEPARTMENT_NO
ORDER BY DEPARTMENT_NO;

--QUESTION_14
SELECT   STUDENT_NAME 동일이름, COUNT(*) "동명인 수"
FROM     TB_STUDENT
GROUP BY STUDENT_NAME
HAVING   COUNT(*) > 1
ORDER BY STUDENT_NAME;

--QUESTION_15
SELECT   NVL( SUBSTR(TERM_NO, 1, 4 ), ' ' ) 년도,
         NVL( SUBSTR(TERM_NO, 5, 2 ), ' ' )학기,
         ROUND( AVG(POINT), 1)
FROM     TB_GRADE
WHERE    STUDENT_NO = 'A112113'
GROUP BY ROLLUP( SUBSTR( TERM_NO, 1, 4 ), SUBSTR( TERM_NO, 5, 2 ) );
