-- DAY5 과제

-- QUESTION 01
SELECT   STUDENT_NAME "학생 이름",
         STUDENT_ADDRESS "주소지"
FROM     TB_STUDENT
ORDER BY 1;

-- QUESTION 02
SELECT   STUDENT_NAME "학생 이름",
         STUDENT_SSN "주민등록번호"
FROM     TB_STUDENT
WHERE    ABSENCE_YN = 'Y'
ORDER BY 2 DESC;

-- QUESTION 03
SELECT   STUDENT_NAME 학생이름,
         STUDENT_NO 학번,
         STUDENT_ADDRESS "거주지 주소"
FROM     TB_STUDENT
WHERE    STUDENT_NO LIKE '9%'
         AND STUDENT_ADDRESS LIKE '경기도%' OR STUDENT_ADDRESS LIKE '%강원도%'
ORDER BY 1;

-- QUESTION 04
SELECT   PROFESSOR_NAME 교수이름,
         PROFESSOR_SSN 주민등록번호
FROM     TB_PROFESSOR
JOIN     TB_DEPARTMENT USING (DEPARTMENT_NO)
WHERE    DEPARTMENT_NO = 005
ORDER BY 2;
----
SELECT   PROFESSOR_NAME 교수이름,
         PROFESSOR_SSN 주민등록번호
FROM     TB_PROFESSOR
WHERE    DEPARTMENT_NO = ( SELECT DEPARTMENT_NO 
                           FROM TB_DEPARTMENT
                           WHERE DEPARTMENT_NO = 005 )
ORDER BY 2;

-- QUESTION 05
SELECT   STUDENT_NO 학생번호,
         TO_CHAR(POINT, 'fm99.00')
FROM     TB_GRADE
WHERE    CLASS_NO = 'C3118100' AND TERM_NO = '200402'
ORDER BY 2 DESC, 1 DESC;

-- QUESTION 06
SELECT   STUDENT_NO 학생번호,
         STUDENT_NAME 학생이름,
         DEPARTMENT_NAME 학과이름
FROM     TB_STUDENT
JOIN     TB_DEPARTMENT USING ( DEPARTMENT_NO )
ORDER BY 2;

-- QUESTION 07
SELECT   CLASS_NAME, DEPARTMENT_NAME
FROM     TB_CLASS C, TB_DEPARTMENT D
WHERE    C.DEPARTMENT_NO = D.DEPARTMENT_NO
ORDER BY 2;

-- QUESTION 08
SELECT   CLASS_NAME,
         PROFESSOR_NAME
FROM     TB_CLASS_PROFESSOR
JOIN     TB_PROFESSOR USING (PROFESSOR_NO)
JOIN     TB_CLASS USING (CLASS_NO);
--GROUP BY CLASS_NAME, PROFESSOR_NAME;

SELECT   C.CLASS_NAME, R.PROFESSOR_NAME
FROM     TB_CLASS_PROFESSOR P, TB_CLASS C, TB_PROFESSOR R
WHERE    P.CLASS_NO = C.CLASS_NO AND P.PROFESSOR_NO = R.PROFESSOR_NO;

-- QUESTION 09
SELECT   CLASS_NAME,
         PROFESSOR_NAME
FROM     TB_CLASS_PROFESSOR
JOIN     TB_CLASS USING (CLASS_NO)
JOIN     TB_DEPARTMENT USING (DEPARTMENT_NO)
JOIN     TB_PROFESSOR USING (PROFESSOR_NO)
WHERE    CATEGORY LIKE '인문사회%';

-- QUESTION 10
SELECT   STUDENT_NO 학번,
         STUDENT_NAME "학생 이름",
         ROUND( AVG(POINT), 1) "전체 평점"
FROM     TB_GRADE
JOIN     TB_STUDENT USING ( STUDENT_NO )
WHERE    DEPARTMENT_NO = '059'
GROUP BY STUDENT_NO, STUDENT_NAME
ORDER BY 3 DESC;

-- QUESTION 11
SELECT   DEPARTMENT_NAME 학과이름,
         STUDENT_NAME 학생이름,
         PROFESSOR_NAME 지도교수이름
FROM     TB_STUDENT
JOIN     TB_DEPARTMENT USING (DEPARTMENT_NO)
JOIN     TB_PROFESSOR ON (PROFESSOR_NO = COACH_PROFESSOR_NO)
WHERE    STUDENT_NO = 'A313047';

-- QUESTION 12
SELECT   STUDENT_NAME,
         TERM_NO
FROM     TB_GRADE
JOIN     TB_STUDENT USING (STUDENT_NO)
JOIN     TB_CLASS USING (CLASS_NO)
WHERE    TERM_NO LIKE '2007%' AND CLASS_NAME = '인간관계론';

-- QUESTION 13
SELECT    CLASS_NAME,
          DEPARTMENT_NAME
FROM      TB_CLASS
JOIN      TB_DEPARTMENT USING (DEPARTMENT_NO)
LEFT JOIN TB_CLASS_PROFESSOR USING (CLASS_NO)
WHERE     CATEGORY LIKE '예체능%' AND PROFESSOR_NO IS NULL; 

-- QUESTION 14
SELECT    STUDENT_NAME 학생이름,
          NVL(PROFESSOR_NAME, '지도교수미지정') 지도교수
FROM      TB_STUDENT
JOIN      TB_DEPARTMENT USING (DEPARTMENT_NO)
LEFT JOIN TB_PROFESSOR ON (COACH_PROFESSOR_NO = PROFESSOR_NO)
WHERE     DEPARTMENT_NAME = ( SELECT  DEPARTMENT_NAME
                             FROM    TB_DEPARTMENT
                             WHERE   DEPARTMENT_NAME LIKE '서반아어%');

-- QUESTION 15
SELECT   /*TB_STUDENT.*/
         STUDENT_NO 학번,
         STUDENT_NAME 이름,
         DEPARTMENT_NAME 학과이름,
         ROUND( AVG(POINT), 8 ) 평점
FROM     TB_GRADE/*, (SELECT STUDENT_NO FROM TB_STUDENT 
          WHERE ABSENCE_YN = 'N')  */
JOIN     TB_STUDENT USING (STUDENT_NO)
JOIN     TB_DEPARTMENT USING (DEPARTMENT_NO)
WHERE    ABSENCE_YN = 'N'  
GROUP BY STUDENT_NO, STUDENT_NAME, DEPARTMENT_NAME
HAVING   AVG(POINT) >= 4.0;


-- QUESTION 16
SELECT   CLASS_NO,
         CLASS_NAME,
         TRUNC( AVG(POINT), 8 ) "AVG(POINT)"
FROM     TB_GRADE
JOIN     TB_CLASS USING (CLASS_NO)
JOIN     TB_DEPARTMENT USING (DEPARTMENT_NO)
WHERE    DEPARTMENT_NAME LIKE '환경조경%' AND CLASS_TYPE LIKE '전공%'
GROUP BY CLASS_NO, CLASS_NAME
ORDER BY 1;

-- QUESTION 17
SELECT   STUDENT_NAME,
         STUDENT_ADDRESS,
         DEPARTMENT_NAME
FROM     TB_STUDENT
JOIN     TB_DEPARTMENT USING (DEPARTMENT_NO)
WHERE    DEPARTMENT_NAME IN ( SELECT  DEPARTMENT_NAME
                              FROM    TB_DEPARTMENT D, TB_STUDENT S
                              WHERE   D.DEPARTMENT_NO = S.DEPARTMENT_NO
                                      AND STUDENT_NAME = '최경희' );


-- QUESTION 18
/*SELECT   STUDENT_NO,
         STUDENT_NAME,
         AVG(POINT)
FROM     TB_GRADE
JOIN     TB_STUDENT USING (STUDENT_NO)
JOIN     TB_DEPARTMENT USING (DEPARTMENT_NO)
WHERE    DEPARTMENT_NAME LIKE '국어%'
GROUP BY STUDENT_NO, STUDENT_NAME
HAVING   AVG(POINT) >ALL (SELECT AVG(POINT) FROM TB_GRADE); */

SELECT   STUDENT_NO, STUDENT_NAME    
FROM     ( SELECT   AVG(POINT), STUDENT_NO, STUDENT_NAME
           FROM     TB_GRADE
           JOIN     TB_STUDENT USING (STUDENT_NO)
           JOIN     TB_DEPARTMENT USING (DEPARTMENT_NO)
           WHERE    DEPARTMENT_NAME LIKE '국어%' 
           GROUP BY STUDENT_NO, STUDENT_NAME
           ORDER BY 1 DESC )
WHERE   ROWNUM = 1;

-- QUESTION 19
SELECT   DEPARTMENT_NAME "계열 학과명",
         ROUND( AVG(POINT), 1 ) 전공평점
FROM     TB_DEPARTMENT
JOIN     TB_STUDENT USING (DEPARTMENT_NO)
JOIN     TB_GRADE USING (STUDENT_NO)
WHERE    DEPARTMENT_NAME IN (SELECT DEPARTMENT_NAME 
                             FROM TB_DEPARTMENT
                             WHERE CATEGORY = '자연과학')
GROUP BY DEPARTMENT_NAME
ORDER BY 1;
