-- 2019.01.14

-- 실습 1
-- 사번, 이름, 급여, 직급명, 부서명, 근무지역명, 소속국가명 조회
-- 조회 결과를 EMP_LIST 테이블에 저장.
CREATE TABLE EMP_LIST
AS SELECT    EMP_ID, EMP_NAME, SALARY, JOB_ID, DEPT_ID, LOC_DESCRIBE, COUNTRY_NAME
   FROM      EMPLOYEE
   JOIN      DEPARTMENT USING (DEPT_ID)
   JOIN      LOCATION ON (LOC_ID = LOCATION_ID)
   JOIN      COUNTRY USING (COUNTRY_ID);
   
SELECT  * FROM EMP_LIST;

-- 실습 2
-- EMPLOYEE 테이블에서 남자 직원의 정보만 조회해서  EMP_MAN테이블에 저장.
CREATE TABLE EMP_MAN
AS SELECT    *
   FROM      EMPLOYEE
   WHERE     SUBSTR(EMP_NO, 8, 1) = '1';
   
SELECT  * FROM EMP_MAN;

DROP TABLE EMP_MAN;

-- 실습 3
-- 여자 직원의 정보만 조회해서 EMP_FEMAIL테이블에 저장.
CREATE TABLE EMP_FEMAIL
AS SELECT   *
   FROM     EMPLOYEE
   WHERE    SUBSTR(EMP_NO, 8, 1) = '2';
   
SELECT  * FROM EMP_FEMAIL;

-- 실습 4
-- 부서별 직원 명단을 정리해서 PART_LIST 테이블에 저장
-- DEPT_NAME, JOB_TILE, EMP_NAME, EMP_ID로 COLUMN 구성
CREATE TABLE PART_LIST
AS SELECT    DEPT_NAME, JOB_TITLE, EMP_NAME, EMP_ID
   FROM      EMPLOYEE E, DEPARTMENT D, JOB J
   WHERE     E.DEPT_ID = D.DEPT_ID(+) AND E.JOB_ID = J.JOB_ID(+)
   ORDER BY  DEPT_NAME;

COMMENT ON COLUMN PART_LIST.DEPT_NAME IS '부서명';
COMMENT ON COLUMN PART_LIST.JOB_TITLE IS '직급명';
COMMENT ON COLUMN PART_LIST.EMP_NAME IS '사원명';
COMMENT ON COLUMN PART_LIST.EMP_ID IS '사원번호';
   
DROP TABLE PART_LIST;
SELECT  * FROM PART_LIST;

-- 실습 : 제약조건이 설정된 테이블 만들기
/*
 테이블명 : PHONEBOOK
 컬럼명 : ID CHAR(3) 기본키(저장이름 : PK_PBID)
 PNAME    VARCHAR2(20) 널 사용못함.
                        (NN_PBNAME)
 PHONE    VARCHAR2(15) 널 사용못함.
                        (NN_PBPHONE)
                        중복값 입력못함.
                        (UN_PBHONE)
 ADDRESS  VARCHAR2(100) 기본값 지정함
                        '서울시 구로구'
 NOT NULL을 제외하고, 모두 테이블 레벨에서 지정함.
*/
CREATE TABLE PHONEBOOK
(
 ID      CHAR(3),
 PNAME   VARCHAR2(20) CONSTRAINT NN_PNAME NOT NULL,
 PHONE   VARCHAR2(15) CONSTRAINT NN_PBPHONE NOT NULL,
 ADDRESS VARCHAR2(100) DEFAULT '서울시 구로구',
 CONSTRAINT PK_PBID PRIMARY KEY (ID),
 CONSTRAINT UN_PBPHONE UNIQUE (PHONE)
);
INSERT INTO PHONEBOOK VALUES ('Br1', '한길준', '010-0000-1111', DEFAULT);
SELECT  * FROM PHONEBOOK;